controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

acheter_produit:
    path: '/produits/{id}/acheter'
    controller: App\Controller\VenteController::acheterProduit
